targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      mockito|mockBuilder:
        generate_for:
          - test/**.dart
          - integration_test/**.dart
    sources:
      - $package$
      - lib/$lib$
      - lib/**.dart
      - test/**.dart
      - integration_test/**.dart