name: the_postraves_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  sprintf: ^6.0.0
  json_annotation: ^4.0.1
  flutter_sticky_header: ^0.6.0
  get_it: ^7.2.0
  another_flushbar: ^1.10.20
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  internet_connection_checker: ^0.0.1+2
  sembast: ^3.0.0+4
  path_provider: ^2.0.1
  path: ^1.8.0
  sliver_tools: ^0.2.1
  ionicons: ^0.1.2
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  cloud_firestore: ^2.5.3
  firebase_messaging: ^10.0.7
  google_sign_in: ^5.0.2
  firebase_dynamic_links: ^2.0.9
  logging: ^1.0.1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.1.0
  image_picker: ^0.8.4+2
  image_cropper: ^1.4.1
  map_launcher: ^2.1.1
  google_static_maps_controller: ^0.6.0
  provider: ^6.0.0
  url_launcher: ^6.0.6
  share_plus: ^2.1.4
  qr_flutter: ^4.0.0
  screen_brightness: ^0.0.4
  mask_text_input_formatter: ^2.0.0
  sign_in_with_apple: ^3.0.0
  crypto: ^3.0.1
  freezed_annotation:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  json_serializable: ^4.1.4
  flutter_native_splash: ^1.2.4
  freezed: ^0.14.2
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # emojis
    - assets/images/emojis/heart_emoji.png
    - assets/images/emojis/fire_emoji.png
    - assets/images/emojis/finish_emoji.png
    - assets/images/emojis/link_emoji.png
    - assets/images/emojis/dizzy_emoji.png
    # images
    - assets/images/map_pin.png
    - assets/images/soundcloud_logo.png
    - assets/images/instagram_logo.png
    - assets/images/telegram_logo.png
    - assets/images/bandcamp_logo.png
    # other assets
    - assets/configs/lunar_landscape_google_map_style.json
    - assets/configs/dark_default_google_map_style.json
    - assets/configs/custom_google_map_style.json

  fonts:
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Thin.ttf
          weight: 100
        - asset: assets/fonts/IBMPlexMono-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/IBMPlexMono-Light.ttf
          weight: 300
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexMono-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexMono-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900

