name: the_postraves_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.0
  flutter_bloc: ^7.1.0
  equatable: ^2.0.3
  sprintf: ^6.0.0
  json_annotation: ^4.0.1
  flutter_sticky_header: ^0.6.0
  get_it: ^7.2.0
  another_flushbar: ^1.10.20
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  internet_connection_checker: ^0.0.1+2
  sembast: ^3.0.0+4
  path_provider: ^2.0.1
  path: ^1.8.0
  sliver_tools: ^0.2.1
  ionicons: ^0.1.2
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  firebase_storage: ^10.0.3
  cloud_firestore: ^2.5.3
  firebase_messaging: ^10.0.7
  google_sign_in: ^5.0.2
  firebase_dynamic_links: ^2.0.9
  logging: ^1.0.1
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.0.0
  image_picker: ^0.8.4
  image_cropper: ^1.4.0
  map_launcher: ^2.1.1
  google_static_maps_controller: ^0.6.0
  provider: ^6.0.0
  url_launcher: ^6.0.6
  share_plus: ^2.1.4
  qr_flutter: ^4.0.0
  screen_brightness: ^0.0.4
  mask_text_input_formatter: ^2.0.0
  freezed_annotation:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  json_serializable: ^4.1.4
  flutter_native_splash: ^1.1.8+4
  freezed: ^0.14.2
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # emojis
    - assets/images/emojis/gem_emoji.png
    - assets/images/emojis/heart_emoji.png
    - assets/images/emojis/calendar_emoji.png
    - assets/images/emojis/money_emoji.png
    - assets/images/emojis/pin_emoji.png
    - assets/images/emojis/crown_emoji.png
    - assets/images/emojis/ticket_emoji.png
    - assets/images/emojis/star_emoji.png
    - assets/images/emojis/fire_emoji.png
    - assets/images/emojis/finish_emoji.png
    - assets/images/emojis/link_emoji.png
    - assets/images/emojis/dizzy_emoji.png
    # emojis country
    - assets/images/emojis/country/belarus_emoji.png
    - assets/images/emojis/country/belgium_emoji.png
    - assets/images/emojis/country/france_emoji.png
    - assets/images/emojis/country/germany_emoji.png
    - assets/images/emojis/country/netherlands_emoji.png
    - assets/images/emojis/country/russia_emoji.png
    - assets/images/emojis/country/ukraine_emoji.png
    # images
    - assets/images/diamond.png
    - assets/images/map_pin.png
    - assets/images/entity_placeholder.png
    - assets/images/event_card_placeholder.png
    - assets/images/soundcloud_logo.png
    - assets/images/instagram_logo.png
    - assets/images/telegram_logo.png
    - assets/images/bandcamp_logo.png
    # other assets
    - assets/configs/lunar_landscape_google_map_style.json
    - assets/configs/dark_default_google_map_style.json
    - assets/configs/custom_google_map_style.json

